# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://github.com/marketplace/actions/setup-node-js-environment

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag, or commit SHA to checkout (optional)'
        required: false

env:
  CI: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 22, 24 ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --ignore-scripts
      - run: npm run ci
